name: AI Push
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run script to update index
        run: |
          node scripts/generate-layout.js
      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add index.html
          git diff --cached --quiet || git commit -m "feat: update about section to grid layout"
          git push origin HEAD:main
