name: AI Push
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm init -y
          npm install cheerio
      - name: Generate layout and update index
        run: |
          echo 'Y29uc3QgZnMgPSByZXF1aXJlKCdmcycpOwpjb25zdCBjaGVlcmlvID0gcmVxdWlyZSgnY2hlZXJpbycpOwoKLy8gUmVhZCB0aGUgaW5kZXguaHRtbCBmaWxlCmNvbnN0IGh0bWwgPSBmcy5yZWFkRmlsZVN5bmMoJ2luZGV4Lmh0bWwnLCAndXRmOCcpOwpjb25zdCAkID0gY2hlZXJpby5sb2FkKGh0bWwpOwoKLy8gRmluZCB0aGUgZmlyc3QgdW5vcmRlcmVkIGxpc3Qgd2l0aCB0aGUgZmVhdHVyZSBsaXN0IGNsYXNzZXMKY29uc3QgdWwgPSAkKCd1bC5saXN0LWRpc2MucGwtNS5zcGFjZS15LTIudGV4dC1iYXNlJykuZmlyc3QoKTsKCmlmICh1bC5sZW5ndGgpIHsKICAvLyBOZXcgZ3JpZCBsYXlvdXQgcmVwbGFjaW5nIHRoZSBsaXN0IGl0ZW1zIHdpdGggaWNvbnMgYW5kIHRyYW5zbGF0aW9uIGtleXMKICBjb25zdCByZXBsYWNlbWVudCA9IGAKPGRpdiBjbGFzcz0iZ3JpZCBncmlkLWNvbHMtMSBzbTpncmlkLWNvbHMtMiBnYXAtNCI+CiAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1zdGFydCBnYXAtMyI+CiAgICA8c3BhbiBjbGFzcz0idGV4dC0yeGwiPvCfm4w8L3NwYW4+CiAgICA8cCBkYXRhLWkxOG49ImFib3V0RmVhdHVyZTEiIGNsYXNzPSJ0ZXh0LWJhc2UiPjwvcD4KICA8L2Rpdj4KICA8ZGl2IGNsYXNzPSJmbGV4IGl0ZW1zLXN0YXJ0IGdhcC0zIj4KICAgIDxzcGFuIGNsYXNzPSJ0ZXh0LTJ4bCI+8J+Nszwvc3Bhbj4KICAgIDxwIGRhdGEtaTE4bj0iYWJvdXRGZWF0dXJlMiIgY2xhc3M9InRleHQtYmFzZSI+PC9wPgogIDwvZGl2PgogIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtc3RhcnQgZ2FwLTMiPgogICAgPHNwYW4gY2xhc3M9InRleHQtMnhsIj7wn5q/PC9zcGFuPgogICAgPHAgZGF0YS1pMThuPSJhYm91dEZlYXR1cmUzIiBjbGFzcz0idGV4dC1iYXNlIj48L3A+CiAgPC9kaXY+CiAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1zdGFydCBnYXAtMyI+CiAgICA8c3BhbiBjbGFzcz0idGV4dC0yeGwiPvCfjIQ8L3NwYW4+CiAgICA8cCBkYXRhLWkxOG49ImFib3V0RmVhdHVyZTQiIGNsYXNzPSJ0ZXh0LWJhc2UiPjwvcD4KICA8L2Rpdj4KICA8ZGl2IGNsYXNzPSJmbGV4IGl0ZW1zLXN0YXJ0IGdhcC0zIj4KICAgIDxzcGFuIGNsYXNzPSJ0ZXh0LTJ4bCI+8J+Ttjwvc3Bhbj4KICAgIDxwIGRhdGEtaTE4bj0iYWJvdXRGZWF0dXJlNSIgY2xhc3M9InRleHQtYmFzZSI+PC9wPgogIDwvZGl2PgogIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtc3RhcnQgZ2FwLTMiPgogICAgPHNwYW4gY2xhc3M9InRleHQtMnhsIj7wn46jPC9zcGFuPgogICAgPHAgZGF0YS1pMThuPSJhYm91dEZlYXR1cmU2IiBjbGFzcz0idGV4dC1iYXNlIj48L3A+CiAgPC9kaXY+CiAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1zdGFydCBnYXAtMyI+CiAgICA8c3BhbiBjbGFzcz0idGV4dC0yeGwiPvCfmq08L3NwYW4+CiAgICA8cCBkYXRhLWkxOG49ImFib3V0RmVhdHVyZTciIGNsYXNzPSJ0ZXh0LWJhc2UgaXRhbGljIj48L3A+CiAgPC9kaXY+CiAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1zdGFydCBnYXAtMyI+CiAgICA8c3BhbiBjbGFzcz0idGV4dC0yeGwiPvCfjLI8L3NwYW4+CiAgICA8cCBkYXRhLWkxOG49ImFib3V0RmVhdHVyZTgiIGNsYXNzPSJ0ZXh0LWJhc2UiPjwvcD4KICA8L2Rpdj4KPC9kaXY+CmA7CiAgLy8gUmVwbGFjZSB0aGUgbGlzdCB3aXRoIHRoZSBuZXcgZ3JpZAogIHVsLnJlcGxhY2VXaXRoKHJlcGxhY2VtZW50LnRyaW0oKSk7CiAgLy8gV3JpdGUgdGhlIHVwZGF0ZWQgSFRNTCBiYWNrIHRvIGluZGV4Lmh0bWwKICBmcy53cml0ZUZpbGVTeW5jKCdpbmRleC5odG1sJywgJC5odG1sKCkpOwogIGNvbnNvbGUubG9nKCdMYXlvdXQgdXBkYXRlZCBzdWNjZXNzZnVsbHkuJyk7Cn0gZWxzZSB7CiAgY29uc29sZS5lcnJvcignRmVhdHVyZSBsaXN0IG5vdCBmb3VuZCBpbiBpbmRleC5odG1sLicpOwogIHByb2Nlc3MuZXhpdCgxKTsKfQo=' | base64 -d > update.js
node -e "global.File = class File {}; require('./update.js')" update.js
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update layout via AI workflow"
            git push origin HEAD:main
          fi
